# Generated by Django 4.1 on 2022-08-04 10:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='postal_code',
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_item', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tags', models.CharField(choices=[('TO', 'Top'), ('SK', 'Skirt'), ('SH', 'Shorts'), ('PA', 'Pants'), ('DR', 'Dress'), ('SE', 'Set'), ('OU', 'Outerwear'), ('AC', 'Accessories')], default='TO', max_length=2)),
                ('date_listed', models.DateField(auto_now=True)),
                ('availability', models.BooleanField()),
                ('clothes_image', models.ImageField(upload_to='post_images')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.users')),
            ],
        ),
    ]
