# Generated by Django 4.1 on 2022-08-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_users_contact_number_remove_users_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='user_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.users'),
        ),
    ]
